# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - chat_history_use
#   # pull_request:
#   #   branches:
#   #     - chat_history_use

# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest

#     services:
#       mongo:
#         image: mongo:latest
#         ports:
#           - 27017:27017

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: "18"

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.13"

#       - name: Install frontend dependencies
#         working-directory: frontend
#         run: npm install

#       - name: Run frontend tests
#         working-directory: frontend
#         run: npm test

#       - name: Build frontend
#         working-directory: frontend
#         run: npm run build

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build-and-test

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Deploy backend
#         working-directory: backend
#         run: |
#           npm install
#           npm start

#       - name: Deploy frontend
#         working-directory: frontend
#         run: |
#           npm install
#           npm run build
#           npm run preview

name: CI Pipeline

on:
  push:
    branches:
      - chat_history_use
  pull_request:
    branches:
      - chat_history_use

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment and install dependencies
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Backend Dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 pip install -r frontend/requirements.txt

    # Step 3: Set up Node.js environment and install frontend dependencies
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm install

    # Step 4: Run Tests
    - name: Run Tests
      run: |
        # Run Python backend tests
        cd frontend
        python -m unittest discover ../tests/ -s tests -p "*.py"

    # Optional: Step 5 for deployment (you can add deployment steps as per your requirements)
    # - name: Deploy Application
    #   run: |
    #     # Add your deployment commands here (e.g., AWS, Heroku, etc.)
    #     echo "Deploying to production..."
